# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CSML @ Cambridge
email: mag92@cam.ac.uk
description: "Pages of the CSML group in the Engineering Department at University of Cambridge"
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages
  - _support_files

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
mathjax: true
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

plugins:
  - jekyll-seo-tag
  - jekyll-feed

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
  math_engine       : mathjax

# Markdown Processing
# kramdown:
#   input: GFM
#   hard_wrap: false
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false
#   parse_block_html: true # default for kramdown is false. This will enable using Markdown links

