
name: Orcid Bibliography downloaded

# Run this workflow 15 minutes
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/60 * * * *'
  push:

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  orcid-sync:
    # Name the Job
    name: This will download publications which are registered on ORCID for every memeber of the group.
    # Set the type of machine to run on
    runs-on: ubuntu-latest 
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      # this Action should follow steps to set up Python build environment
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: 2.9.1
      - name: Run the Orcid Updater script
        run: python pull_publications_orcid.py
        env:
          DEFAULT_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORCID_CLIENT_ID: ${{secrets.ORCID_CLIENT_ID}}
          ORCID_CLIENT_SECRET: ${{secrets.ORCID_CLIENT_SECRET}}
      - name: check for changes
        run: git status
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
        # You can now access a variable indicating if there have been changes
      - name: Process changes
        if: steps.changes.outputs.changed == 1
        run: |
          echo "Changes exist"
          git add .
          git config --global user.email "jan.povala@gmail.com"
          git config --global user.name "The deployment agent"
          git commit -m "Auto updating TODO.txt"
          git pull origin master
          git push origin HEAD:master
        
