
name: Orcid Bibliography downloaded

# Run this workflow 15 minutes
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'
  push:

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  orcid-sync:
    # Name the Job
    name: This will download publications which are registered on ORCID for every memeber of the group.
    # Set the type of machine to run on
    runs-on: ubuntu-latest 
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      # this Action should follow steps to set up Python build environment
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
      - name: Run the Orcid Updater script
        run: pull_publications_orcid.py
        shell: python
        env:
          DEFAULT_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORCID_CLIENT_ID: ${{secrets.ORCID_CLIENT_ID}}
          ORCID_CLIENT_PASWORD: ${{secrets.ORCID_CLIENT_SECRET}}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating TODO.txt"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
        
